"""Run per-sample and cohort-level QC for one scRNA-seq GEO study.

The script reads the reproducible sample manifest generated by
``build_metadata.py`` and processes samples sequentially to keep memory usage
bounded.  Input matrices are never overwritten.

Example:
    python run_sc_eda.py --study-id GSE179640
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

# Keep Matplotlib caches inside the writable project output directory.
os.environ.setdefault("MPLCONFIGDIR", str(Path("output/.matplotlib_cache").resolve()))

import pandas as pd

from src.eda import (
    QCThresholds,
    calculate_qc,
    filter_sample,
    plot_cohort_qc,
    plot_sample_qc,
    read_sample,
    summarize_sample,
    write_thresholds,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run documented single-cell QC and EDA.")
    parser.add_argument("--study-id", default="GSE179640", help="GEO study to analyze")
    parser.add_argument("--metadata", type=Path, default=Path("output/reports/sample_metadata.csv"))
    parser.add_argument("--output-dir", type=Path, default=Path("output"))
    parser.add_argument("--min-genes", type=int, default=200, help="Minimum detected genes per cell")
    parser.add_argument("--max-genes", type=int, default=None, help="Optional maximum detected genes per cell")
    parser.add_argument("--max-pct-mito", type=float, default=20.0, help="Maximum mitochondrial percentage")
    parser.add_argument("--min-cells-per-gene", type=int, default=3)
    parser.add_argument("--min-cells-after-qc", type=int, default=200, help="Flag smaller samples for review")
    parser.add_argument("--min-retention-pct", type=float, default=50.0, help="Flag lower-retention samples")
    parser.add_argument("--limit", type=int, default=None, help="Process only the first N samples for a smoke test")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    thresholds = QCThresholds(
        min_genes_per_cell=args.min_genes,
        max_genes_per_cell=args.max_genes,
        max_pct_mito=args.max_pct_mito,
        min_cells_per_gene=args.min_cells_per_gene,
        min_cells_after_qc=args.min_cells_after_qc,
        min_cell_retention_pct=args.min_retention_pct,
    )
    thresholds.validate()

    metadata = pd.read_csv(args.metadata, keep_default_na=False)
    selected = metadata.loc[
        (metadata["study_id"] == args.study_id)
        & (metadata["technology"] == "scRNA-seq")
        & (metadata["include_in_sc_eda"].astype(str).str.lower() == "true")
    ].sort_values("sample_id")
    if args.limit is not None:
        selected = selected.head(args.limit)
    if selected.empty:
        raise SystemExit(f"No eligible scRNA-seq samples found for {args.study_id}")

    per_sample_dir = args.output_dir / "eda_plots" / "per_sample" / args.study_id
    cohort_dir = args.output_dir / "eda_plots" / "cohort" / args.study_id
    reports_dir = args.output_dir / "reports" / "qc" / args.study_id
    write_thresholds(reports_dir / "qc_thresholds.json", thresholds)

    summaries = []
    errors = []
    print(f"Processing {len(selected)} samples from {args.study_id}")
    for index, (_, row) in enumerate(selected.iterrows(), start=1):
        sample_id = row["sample_id"]
        print(f"[{index}/{len(selected)}] {sample_id}", flush=True)
        try:
            adata = calculate_qc(read_sample(row))
            filtered = filter_sample(adata, thresholds)
            summaries.append(summarize_sample(adata, filtered, row, thresholds))
            plot_sample_qc(adata, sample_id, per_sample_dir / f"{sample_id}_qc.png")
        except Exception as exc:  # Continue to produce an auditable error report.
            errors.append({"sample_id": sample_id, "error_type": type(exc).__name__, "message": str(exc)})

    if not summaries:
        raise SystemExit("All samples failed; inspect qc_processing_errors.csv")

    summary = pd.DataFrame(summaries).sort_values("sample_id")
    reports_dir.mkdir(parents=True, exist_ok=True)
    summary.to_csv(reports_dir / "qc_sample_summary.csv", index=False)
    summary.loc[summary["qc_status"] == "review"].to_csv(reports_dir / "qc_flagged_samples.csv", index=False)
    pd.DataFrame(errors, columns=["sample_id", "error_type", "message"]).to_csv(
        reports_dir / "qc_processing_errors.csv", index=False
    )
    plot_cohort_qc(summary, cohort_dir)

    print(f"Completed: {len(summary)} samples; failed: {len(errors)}")
    print(f"Flagged for review: {(summary['qc_status'] == 'review').sum()}")
    print(f"Reports: {reports_dir}")


if __name__ == "__main__":
    main()
